services:
  mongo-db:
    image: mongo:5.0.26
    container_name: mongo-db 
    restart: always
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-admin}
    ports:
      - "9899:27017"

  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   restart: always
  #   environment:
  #     - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
  #     - MONGO_DB_NAME=${MONGO_DB_NAME}
  #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  #   ports:
  #     - "1998:80"
  #   depends_on:
  #     - mongo-db

  # frontend:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "3001:80"
  #   depends_on:
  #     - backend

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - "3002:6379"

  # celery:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: celery
  #   restart: always
  #   environment:
  #     - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
  #     - MONGO_DB_NAME=${MONGO_DB_NAME}
  #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  #     - REDIS_URL=redis://redis:3002/0
  #   depends_on:
  #     - redis
  #     - mongo-db