

version: '3.7'


services:
  db:
    image: mongo:5.0.26
    container_name: mongo
    restart: always
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
    ports:
      - "9898:8081"
    depends_on:
      - db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "1998:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend